language: android
jdk: oraclejdk8
sudo: enabled
install:
      sudo apt-get install ruby-full
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-24
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

before_script:
      - gem install calabash-android
      - keytool -genkey -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
      - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 32M
      - emulator -avd test -no-audio -no-window &
      - android-wait-for-emulator
script:
      calabash-android resign features/netq.apk 
      calabash-android run features/netq.apk    
