language: android
jdk: oraclejdk8

sudo: enabled

install:
      sudo apt-get install ruby-full

before_script:
      - gem install calabash-android

      - keytool -genkey -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
script:
      calabash-android resign features/netq.apk      