language: android
jdk: oraclejdk8
sudo: enabled
install:
      sudo apt-get install ruby-full
android:
 components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
before_script:
      - gem install calabash-android

      - keytool -genkey -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
      - emulator -avd test -no-skin -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
script:
      calabash-android resign features/netq.apk 
      calabash-android run features/netq.apk    
