language: android
jdk: oraclejdk8

sudo: enabled

install:
      sudo apt-get install ruby-full

before_script:
      gem install calabash-android
script:
      calabash-android resign features/netq.apk      